-- Auto-generated by scripts/generate_github_projects_sync_sql.mjs

-- Sync selected GitHub repositories into public.projects

begin;

with incoming as (
    select
        'F5 TTS Voice Chat v2'::text as title,
        'F5-TTS Voice Chat with Whisper STT and Ollama LLM'::text as description,
        'https://github.com/yishu-ziyu/f5-tts-voice-chat-v2'::text as repo_url,
        ARRAY['Python', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/f5-tts-voice-chat-v2'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/f5-tts-voice-chat-v2

F5-TTS Voice Chat with Whisper STT and Ollama LLM

## Snapshot
- Repository: https://github.com/yishu-ziyu/f5-tts-voice-chat-v2
- Last Updated (UTC): 2026-02-22
- Language: Python
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'Logic Arena'::text as title,
        'Logic Arena 正在持续开发中，详细进展请查看 GitHub 仓库。'::text as description,
        'https://github.com/yishu-ziyu/logic-arena'::text as repo_url,
        ARRAY['TypeScript', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/logic-arena'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/logic-arena

Logic Arena 正在持续开发中，详细进展请查看 GitHub 仓库。

## Snapshot
- Repository: https://github.com/yishu-ziyu/logic-arena
- Last Updated (UTC): 2026-02-21
- Language: TypeScript
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'Aegis Manim'::text as title,
        'Aegis Manim 正在持续开发中，详细进展请查看 GitHub 仓库。'::text as description,
        'https://github.com/yishu-ziyu/Aegis-Manim'::text as repo_url,
        ARRAY['Python', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/Aegis-Manim'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/Aegis-Manim

Aegis Manim 正在持续开发中，详细进展请查看 GitHub 仓库。

## Snapshot
- Repository: https://github.com/yishu-ziyu/Aegis-Manim
- Last Updated (UTC): 2026-02-21
- Language: Python
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'Recall Sticker'::text as title,
        'Recall Sticker 正在持续开发中，详细进展请查看 GitHub 仓库。'::text as description,
        'https://github.com/yishu-ziyu/Recall-Sticker'::text as repo_url,
        ARRAY['JavaScript', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/Recall-Sticker'::text as image_url,
        '2026'::text as year,
        1::integer as stars,
        '# yishu-ziyu/Recall-Sticker

Recall Sticker 正在持续开发中，详细进展请查看 GitHub 仓库。

## Snapshot
- Repository: https://github.com/yishu-ziyu/Recall-Sticker
- Last Updated (UTC): 2026-01-27
- Language: JavaScript
- Stars: 1
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'Mirror Self Monitor'::text as title,
        'Mirror: A tool to manage honesty, not just time. 拒绝大脑美化，直面真实产出。'::text as description,
        'https://github.com/yishu-ziyu/mirror-self-monitor'::text as repo_url,
        ARRAY['HTML', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/mirror-self-monitor'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/mirror-self-monitor

Mirror: A tool to manage honesty, not just time. 拒绝大脑美化，直面真实产出。

## Snapshot
- Repository: https://github.com/yishu-ziyu/mirror-self-monitor
- Last Updated (UTC): 2026-01-24
- Language: HTML
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'YiShu SVG'::text as title,
        'YiShu SVG - 智能教学动画生成器：用自然语言生成动态 SVG 动画'::text as description,
        'https://github.com/yishu-ziyu/yishu-svg'::text as repo_url,
        ARRAY['HTML', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/yishu-svg'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/yishu-svg

YiShu SVG - 智能教学动画生成器：用自然语言生成动态 SVG 动画

## Snapshot
- Repository: https://github.com/yishu-ziyu/yishu-svg
- Last Updated (UTC): 2026-01-21
- Language: HTML
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'QuestSpace 2.0'::text as title,
        'AI-powered knowledge graph whiteboard inspired by Heptabase'::text as description,
        'https://github.com/yishu-ziyu/questspace-2.0'::text as repo_url,
        ARRAY['TypeScript', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/questspace-2.0'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/questspace-2.0

AI-powered knowledge graph whiteboard inspired by Heptabase

## Snapshot
- Repository: https://github.com/yishu-ziyu/questspace-2.0
- Last Updated (UTC): 2026-01-20
- Language: TypeScript
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'Learn Your Way'::text as title,
        'AI-augmented textbook platform with personalized, multi-modal learning experiences'::text as description,
        'https://github.com/yishu-ziyu/learn-your-way'::text as repo_url,
        ARRAY['TypeScript', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/learn-your-way'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/learn-your-way

AI-augmented textbook platform with personalized, multi-modal learning experiences

## Snapshot
- Repository: https://github.com/yishu-ziyu/learn-your-way
- Last Updated (UTC): 2026-01-20
- Language: TypeScript
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

with incoming as (
    select
        'NewsNow Yi'::text as title,
        'NewsNow Yi 正在持续开发中，详细进展请查看 GitHub 仓库。'::text as description,
        'https://github.com/yishu-ziyu/newsnow-yi'::text as repo_url,
        ARRAY['TypeScript', 'GitHub']::text[] as tech_stack,
        'https://opengraph.githubassets.com/1/yishu-ziyu/newsnow-yi'::text as image_url,
        '2026'::text as year,
        0::integer as stars,
        '# yishu-ziyu/newsnow-yi

NewsNow Yi 正在持续开发中，详细进展请查看 GitHub 仓库。

## Snapshot
- Repository: https://github.com/yishu-ziyu/newsnow-yi
- Last Updated (UTC): 2026-01-12
- Language: TypeScript
- Stars: 0
- Forks: 0

## Notes
- This project card is synced from GitHub metadata.
- You can further edit the description and details in the admin panel.'::text as content,
        'published'::text as status
),
updated as (
    update public.projects p
    set
        title = i.title,
        description = i.description,
        tech_stack = i.tech_stack,
        image_url = i.image_url,
        year = i.year,
        stars = i.stars,
        content = i.content,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.repo_url = i.repo_url
    returning p.id
)
insert into public.projects (
    title,
    description,
    repo_url,
    tech_stack,
    image_url,
    year,
    stars,
    content,
    status
)
select
    i.title,
    i.description,
    i.repo_url,
    i.tech_stack,
    i.image_url,
    i.year,
    i.stars,
    i.content,
    i.status
from incoming i
where not exists (select 1 from updated);

commit;
