#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';

const ROOT = process.cwd();
const CONSTANTS_TS = path.resolve(ROOT, 'constants.ts');
const TMP_BUNDLE = path.resolve('/tmp', 'yishu_constants_for_sync.cjs');
const OUTPUT_SQL = path.resolve(ROOT, 'supabase/sync_articles_papers.sql');

function quote(value) {
    if (value == null) {
        return 'NULL';
    }
    return `'${String(value).replace(/'/g, "''")}'`;
}

function toTextArray(list) {
    if (!Array.isArray(list) || list.length === 0) {
        return "ARRAY[]::text[]";
    }
    return `ARRAY[${list.map((item) => quote(item)).join(', ')}]::text[]`;
}

function toIsoFromMs(ms) {
    if (typeof ms !== 'number' || Number.isNaN(ms)) {
        return null;
    }
    return new Date(ms).toISOString();
}

function articleUpsertSQL(article) {
    const createdAtIso = toIsoFromMs(article.createdAt);
    return `
with incoming as (
    select
        ${quote(article.title)}::text as title,
        ${quote(article.excerpt)}::text as excerpt,
        ${quote(article.content)}::text as content,
        ${quote(article.pdfUrl ?? null)}::text as pdf_url,
        ${quote(article.externalUrl ?? null)}::text as external_url,
        ${toTextArray(article.tags)} as tags,
        ${quote(article.status ?? 'draft')}::text as status,
        ${quote(createdAtIso)}::timestamptz as created_at
),
updated as (
    update public.articles a
    set
        excerpt = i.excerpt,
        content = i.content,
        pdf_url = i.pdf_url,
        external_url = i.external_url,
        tags = i.tags,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where a.title = i.title
    returning a.id
)
insert into public.articles (
    title,
    excerpt,
    content,
    pdf_url,
    external_url,
    tags,
    status,
    created_at
)
select
    i.title,
    i.excerpt,
    i.content,
    i.pdf_url,
    i.external_url,
    i.tags,
    i.status,
    coalesce(i.created_at, timezone('utc', now()))
from incoming i
where not exists (select 1 from updated);
`.trim();
}

function paperUpsertSQL(paper) {
    const createdAtIso = toIsoFromMs(paper.createdAt);
    return `
with incoming as (
    select
        ${quote(paper.title)}::text as title,
        ${quote(paper.abstract)}::text as abstract,
        ${quote(paper.journal)}::text as journal,
        ${quote(paper.pdfUrl ?? null)}::text as pdf_url,
        ${quote(paper.imageUrl)}::text as image_url,
        ${quote(paper.year)}::text as year,
        ${quote(paper.category)}::text as category,
        ${quote(paper.status ?? 'draft')}::text as status,
        ${quote(createdAtIso)}::timestamptz as created_at
),
updated as (
    update public.papers p
    set
        abstract = i.abstract,
        journal = i.journal,
        pdf_url = i.pdf_url,
        image_url = i.image_url,
        year = i.year,
        category = i.category,
        status = i.status,
        updated_at = timezone('utc', now())
    from incoming i
    where p.title = i.title
    returning p.id
)
insert into public.papers (
    title,
    abstract,
    journal,
    pdf_url,
    image_url,
    year,
    category,
    status,
    created_at
)
select
    i.title,
    i.abstract,
    i.journal,
    i.pdf_url,
    i.image_url,
    i.year,
    i.category,
    i.status,
    coalesce(i.created_at, timezone('utc', now()))
from incoming i
where not exists (select 1 from updated);
`.trim();
}

async function loadConstants() {
    await build({
        entryPoints: [CONSTANTS_TS],
        bundle: true,
        platform: 'node',
        format: 'cjs',
        outfile: TMP_BUNDLE,
        logLevel: 'silent',
    });

    const mod = await import(pathToFileURL(TMP_BUNDLE).href);
    return mod.default ?? mod;
}

async function main() {
    const data = await loadConstants();
    const articles = data.INITIAL_ARTICLES ?? [];
    const papers = data.INITIAL_PAPERS ?? [];

    const sql = [
        '-- Auto-generated by scripts/generate_articles_papers_sync_sql.mjs',
        '-- Sync articles and papers from constants.ts into Supabase',
        'begin;',
        ...articles.map(articleUpsertSQL),
        ...papers.map(paperUpsertSQL),
        'commit;',
    ].join('\n\n');

    await fs.writeFile(OUTPUT_SQL, `${sql}\n`, 'utf8');
    console.log(`Generated ${OUTPUT_SQL}`);
    console.log(`Articles: ${articles.length}, Papers: ${papers.length}`);
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});

